// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/8/2026, 3:09:48 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/AIUser/Desktop/Opencode/Landingpage2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/plugins/**/*.{js,ts,mjs}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/composables/**/*.{js,ts,mjs}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/utils/**/*.{js,ts,mjs}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/AIUser/Desktop/Opencode/Landingpage2/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;